import type { PetAnimationKey } from '../../assets/manifest'
import type { PetReactionId } from '../../../types/pet'

export type MotionMood = 'soft' | 'eager' | 'wary' | 'reject' | 'sleepy' | 'playful' | 'magic'

export type PetMotionProfile = {
  animation: PetAnimationKey
  mood: MotionMood
  lean: number
  hop: number
  squash: number
  settleMs: number
}

export type PetMotionPhase = PetMotionProfile & {
  at: number
  label: string
}

export const REACTION_MOTIONS: Record<PetReactionId, PetMotionProfile> = {
  eat_excited: {
    animation: 'feed',
    mood: 'eager',
    lean: -5,
    hop: 16,
    squash: 0.08,
    settleMs: 170,
  },
  eat_careful: {
    animation: 'feed',
    mood: 'wary',
    lean: 3,
    hop: 4,
    squash: 0.03,
    settleMs: 260,
  },
  sniff_ignore_food: {
    animation: 'feed',
    mood: 'reject',
    lean: 8,
    hop: 0,
    squash: 0.02,
    settleMs: 280,
  },
  purr_accept: {
    animation: 'pet_head',
    mood: 'soft',
    lean: -3,
    hop: 5,
    squash: 0.04,
    settleMs: 240,
  },
  slow_blink_accept: {
    animation: 'pet_head',
    mood: 'sleepy',
    lean: 1,
    hop: 2,
    squash: 0.03,
    settleMs: 360,
  },
  ask_feed: {
    animation: 'attention',
    mood: 'wary',
    lean: -4,
    hop: 8,
    squash: 0.04,
    settleMs: 220,
  },
  overpetted_tail: {
    animation: 'pet_head',
    mood: 'reject',
    lean: 10,
    hop: 3,
    squash: 0.02,
    settleMs: 320,
  },
  head_bump: {
    animation: 'pet_head',
    mood: 'soft',
    lean: -10,
    hop: 8,
    squash: 0.05,
    settleMs: 210,
  },
  shy_cheek: {
    animation: 'cheek',
    mood: 'soft',
    lean: -5,
    hop: 6,
    squash: 0.05,
    settleMs: 240,
  },
  cheek_reject: {
    animation: 'cheek',
    mood: 'reject',
    lean: 9,
    hop: 2,
    squash: 0.02,
    settleMs: 300,
  },
  zoomies: {
    animation: 'play',
    mood: 'playful',
    lean: -8,
    hop: 20,
    squash: 0.09,
    settleMs: 120,
  },
  lazy_play_reject: {
    animation: 'sleep',
    mood: 'sleepy',
    lean: 2,
    hop: 0,
    squash: 0.03,
    settleMs: 350,
  },
  hungry_play_distracted: {
    animation: 'attention',
    mood: 'wary',
    lean: -3,
    hop: 6,
    squash: 0.04,
    settleMs: 240,
  },
  curl_sleep: {
    animation: 'sleep',
    mood: 'sleepy',
    lean: 0,
    hop: 0,
    squash: 0.05,
    settleMs: 420,
  },
  wake_stretch: {
    animation: 'happy',
    mood: 'soft',
    lean: -9,
    hop: 7,
    squash: 0.1,
    settleMs: 260,
  },
  sleepy_refuse_wake: {
    animation: 'sleep',
    mood: 'sleepy',
    lean: 5,
    hop: 0,
    squash: 0.02,
    settleMs: 360,
  },
  resist_sleep: {
    animation: 'play',
    mood: 'playful',
    lean: -6,
    hop: 10,
    squash: 0.06,
    settleMs: 180,
  },
  dream_soft: {
    animation: 'dream',
    mood: 'magic',
    lean: 0,
    hop: 6,
    squash: 0.03,
    settleMs: 320,
  },
  dream_guard: {
    animation: 'dream',
    mood: 'magic',
    lean: -4,
    hop: 10,
    squash: 0.04,
    settleMs: 260,
  },
}

export const REACTION_SEQUENCES: Partial<Record<PetReactionId, PetMotionPhase[]>> = {
  curl_sleep: [
    {
      at: 0,
      label: 'notice_safe_place',
      animation: 'pet_head',
      mood: 'sleepy',
      lean: 1,
      hop: 0,
      squash: 0.03,
      settleMs: 420,
    },
    {
      at: 900,
      label: 'turn_into_loaf',
      animation: 'sleep',
      mood: 'sleepy',
      lean: -2,
      hop: 0,
      squash: 0.05,
      settleMs: 520,
    },
    {
      at: 2_200,
      label: 'deep_sleep_breathing',
      animation: 'sleep',
      mood: 'sleepy',
      lean: 0,
      hop: 0,
      squash: 0.015,
      settleMs: 680,
    },
  ],
  wake_stretch: [
    {
      at: 0,
      label: 'sleepy_notice',
      animation: 'sleep',
      mood: 'sleepy',
      lean: 0,
      hop: 0,
      squash: 0.02,
      settleMs: 420,
    },
    {
      at: 750,
      label: 'slow_stretch',
      animation: 'happy',
      mood: 'soft',
      lean: -12,
      hop: 4,
      squash: 0.12,
      settleMs: 680,
    },
    {
      at: 1_800,
      label: 'shake_off_sleep',
      animation: 'play',
      mood: 'playful',
      lean: 8,
      hop: 10,
      squash: 0.07,
      settleMs: 260,
    },
    {
      at: 2_650,
      label: 'soft_settle',
      animation: 'idle',
      mood: 'soft',
      lean: 0,
      hop: 0,
      squash: 0.018,
      settleMs: 500,
    },
  ],
  sleepy_refuse_wake: [
    {
      at: 0,
      label: 'one_eye_open',
      animation: 'attention',
      mood: 'sleepy',
      lean: 2,
      hop: 1,
      squash: 0.02,
      settleMs: 460,
    },
    {
      at: 900,
      label: 'curl_back_up',
      animation: 'sleep',
      mood: 'sleepy',
      lean: 4,
      hop: 0,
      squash: 0.04,
      settleMs: 620,
    },
  ],
  eat_excited: [
    {
      at: 0,
      label: 'notice_food',
      animation: 'attention',
      mood: 'eager',
      lean: -7,
      hop: 8,
      squash: 0.05,
      settleMs: 180,
    },
    {
      at: 520,
      label: 'rush_to_bowl',
      animation: 'play',
      mood: 'eager',
      lean: -10,
      hop: 12,
      squash: 0.08,
      settleMs: 180,
    },
    {
      at: 1_100,
      label: 'eat_then_happy',
      animation: 'feed',
      mood: 'soft',
      lean: -2,
      hop: 2,
      squash: 0.04,
      settleMs: 340,
    },
  ],
  purr_accept: [
    {
      at: 0,
      label: 'notice_hand',
      animation: 'attention',
      mood: 'soft',
      lean: -2,
      hop: 3,
      squash: 0.02,
      settleMs: 230,
    },
    {
      at: 560,
      label: 'lean_into_hand',
      animation: 'pet_head',
      mood: 'soft',
      lean: -9,
      hop: 4,
      squash: 0.04,
      settleMs: 420,
    },
    {
      at: 1_450,
      label: 'slow_blink_purr',
      animation: 'happy',
      mood: 'soft',
      lean: 0,
      hop: 2,
      squash: 0.02,
      settleMs: 520,
    },
  ],
  overpetted_tail: [
    {
      at: 0,
      label: 'freeze_and_notice',
      animation: 'attention',
      mood: 'wary',
      lean: 2,
      hop: 0,
      squash: 0.015,
      settleMs: 200,
    },
    {
      at: 500,
      label: 'turn_away',
      animation: 'pet_head',
      mood: 'reject',
      lean: 12,
      hop: 2,
      squash: 0.02,
      settleMs: 280,
    },
    {
      at: 1_300,
      label: 'tail_thump_settle',
      animation: 'attention',
      mood: 'reject',
      lean: -8,
      hop: 0,
      squash: 0.025,
      settleMs: 220,
    },
  ],
  zoomies: [
    {
      at: 0,
      label: 'crouch_wiggle',
      animation: 'attention',
      mood: 'playful',
      lean: -5,
      hop: 4,
      squash: 0.1,
      settleMs: 200,
    },
    {
      at: 520,
      label: 'pounce_run',
      animation: 'play',
      mood: 'playful',
      lean: -12,
      hop: 20,
      squash: 0.11,
      settleMs: 130,
    },
    {
      at: 1_850,
      label: 'happy_recover',
      animation: 'happy',
      mood: 'soft',
      lean: 2,
      hop: 6,
      squash: 0.04,
      settleMs: 360,
    },
  ],
  dream_soft: [
    {
      at: 0,
      label: 'settle_into_dream',
      animation: 'sleep',
      mood: 'sleepy',
      lean: 0,
      hop: 0,
      squash: 0.02,
      settleMs: 500,
    },
    {
      at: 900,
      label: 'dream_spark',
      animation: 'dream',
      mood: 'magic',
      lean: 0,
      hop: 8,
      squash: 0.03,
      settleMs: 520,
    },
  ],
  dream_guard: [
    {
      at: 0,
      label: 'alert_to_dream',
      animation: 'attention',
      mood: 'wary',
      lean: -4,
      hop: 5,
      squash: 0.03,
      settleMs: 280,
    },
    {
      at: 760,
      label: 'guardian_pulse',
      animation: 'dream',
      mood: 'magic',
      lean: -8,
      hop: 12,
      squash: 0.04,
      settleMs: 360,
    },
  ],
}
