// This file is generated by scripts/generate-cat-variants.mjs.
// Add folders under public/assets/pet/cat_actions/run and restart dev/build to update it.
export const GENERATED_CAT_VARIANTS = [
  {
    id: 'abyssinian',
    label: 'Abyssinian',
    runFolder: '1-Abyssinian-lengend',
    runFileStem: 'Abyssinian-lengend'
  },
  {
    id: 'american_bobtail',
    label: 'American Bobtail',
    runFolder: '2-American_Bobtail-lengend',
    runFileStem: 'American_Bobtail-lengend'
  },
  {
    id: 'american_curl',
    label: 'American Curl',
    runFolder: '3-American_Curl-lengend',
    runFileStem: 'American_Curl-lengend'
  },
  {
    id: 'balinese',
    label: 'Balinese',
    runFolder: '4-Balinese-lengend',
    runFileStem: 'Balinese-lengend'
  }
] as const
